name: Terraform Infra Pipeline with Parameters
trigger: none
pool: default

steps:
- task: TerraformTask@5
  displayName: Terraform init
  condition: eq('${{ parameters.task }}', 'dev')
  inputs:
    provider: 'azurerm'
    command: 'init'
    
    workingDirectory: '$(System.DefaultWorkingDirectory)/pre-prod-Module'
    backendServiceArm: 'cptestazuresvc'
    backendAzureRmStorageAccountName: 'hcl9999999'
    backendAzureRmContainerName: 'hclcontainer'
    backendAzureRmKey: 'cp.tfstate'

- task: TerraformTask@5
  displayName: Terraform plan
  condition: eq('${{ parameters.task }}', 'plan')
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/pre-prod-Module'
    environmentServiceNameAzureRM: 'cptestazuresvc'

- task: TerraformTask@5
  displayName: Terraform apply
  condition: eq('${{ parameters.task }}', 'apply')
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/pre-prod-Module'
    environmentServiceNameAzureRM: 'cptestazuresvc'
