name: Terraform parameter pipeline
trigger: none
pool: default

parameters:
- name: task
  displayName: Choose Task
  type: string
  default: apply
  values: 
  - init
  - plan
  - apply

variables: 
  dev-env-wd: '$(System.DefaultWorkingDirectory)/dev-Module'  
steps:
- task: TerraformTask@5
  displayName: Terraform init
  condition: ne('${{ parameters.task }}', 'init')

  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(dev-env-wd)'
    backendServiceArm: 'cptestazuresvc'
    backendAzureRmStorageAccountName: 'hcl9999999'
    backendAzureRmContainerName: 'hclcontainer'
    backendAzureRmKey: 'cp.tfstate'

- task: TerraformTask@5
  displayName: Terraform plan
  condition: ne('${{ parameters.task }}', 'init')
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(dev-env-wd)'
    environmentServiceNameAzureRM: 'cptestazuresvc'

- task: TerraformTask@5
  displayName: Terraform apply
  condition: ne('${{ parameters.task }}', 'init')
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(dev-env-wd)'
    environmentServiceNameAzureRM: 'cptestazuresvc'
