name: Terraform parameter pipeline
trigger: none
pool: default


parameters:
- name: env
  displayName: Choose env
  type: string
  default: dev
  values: 
  - dev
  - pre-prod
  - prod

variables:
  workingDir: '$(System.DefaultWorkingDirectory)/${{ parameters.env }}-Module'
  stateFileName: '${{ parameters.env }}-cp.tfstate'
  

steps:
- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(workingDir)'
    backendServiceArm: 'cptestazuresvc'
    backendAzureRmStorageAccountName: 'hcl9999999'
    backendAzureRmContainerName: 'hclcontainer'
    backendAzureRmKey: '$(stateFileName)'
- task: TerraformTask@5
  displayName: Terraform plan
  
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(workingDir)'
    environmentServiceNameAzureRM: 'cptestazuresvc'

- task: TerraformTask@5
  displayName: Terraform apply
  # condition: ne('${{ parameters.task }}', 'init')
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(workingDir)'
    environmentServiceNameAzureRM: 'cptestazuresvc'
