name: Terraform Multi-Env Pipeline

on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Apply infrastructure? (true/false)'
        required: true
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  terraform:
    name: Test Terraform for each env
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, pre-prod, prod]

    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false

    defaults:
      run:
        working-directory: terraform/envs/${{ matrix.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # use your desired version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.apply == 'true'
        run: terraform apply -auto-approve tfplan
